import path from "node:path";
import { convertJSDocComment } from "./comments";
import {
  generateImmutableInterfaceCode,
  generateImportBlock,
  generateSchemaCode,
} from "./generate-code";
import type { FilePaths, InputFileInfo } from "./types";
import { SetMap } from "./utils";

const GENERATED_FILE_HEADER =
  "// This file is auto-generated by @sw-file-lib/dev-tools/xml-schema-codegen. Do not edit.";

export function createFilePaths(inputFileInfo: InputFileInfo, outDir: string): FilePaths {
  return {
    schema: path.join(outDir, `${inputFileInfo.name}-schema.ts`),
    mutableInterface: inputFileInfo.path,
    immutableInterface: path.join(outDir, `${inputFileInfo.name}-immutable.ts`),
  };
}

export function generateSchemaFile(
  inputFile: InputFileInfo,
  filePaths: FilePaths,
  options: { xImportStatement?: string },
): string {
  const commentImports = new SetMap<string, string>();

  const body = inputFile.schemas
    .map(
      (s) =>
        convertJSDocComment(s, commentImports, {
          filePaths,
          target: "schema",
          see: ["mutableInterface", "immutableInterface"],
        }) +
        "\n" +
        generateSchemaCode(s) +
        "\n",
    )
    .join("\n");

  const schemaImports = new SetMap<string, string>();
  for (const [path, symbols] of inputFile.schemaImports.entries()) {
    for (const symbol of symbols) {
      schemaImports.add(`${path}-schema`, `${symbol}Schema`);
    }
  }

  const importBlock = generateImportBlock({
    imports: schemaImports,
    commentImports,
    importStatements: options.xImportStatement ? [options.xImportStatement] : undefined,
  });

  return GENERATED_FILE_HEADER + "\n\n" + importBlock + "\n\n" + body;
}

export function generateImmutableInterfaceFile(
  inputFile: InputFileInfo,
  filePaths: FilePaths,
): string {
  const commentImports = new SetMap<string, string>();

  const body = inputFile.schemas
    .map(
      (s) =>
        convertJSDocComment(s, commentImports, {
          filePaths,
          target: "immutableInterface",
          see: ["schema", "mutableInterface"],
        }) +
        "\n" +
        generateImmutableInterfaceCode(s) +
        "\n",
    )
    .join("\n");

  const immutableImports = new SetMap<string, string>();
  for (const [path, symbols] of inputFile.schemaImports.entries()) {
    for (const symbol of symbols) {
      immutableImports.add(`${path}-immutable`, `${symbol}Immutable`);
    }
  }

  const importBlock = generateImportBlock({
    typeImports: immutableImports,
    commentImports,
  });

  return GENERATED_FILE_HEADER + "\n\n" + importBlock + "\n\n" + body;
}
