export const BASIC_BLOCK_SURFACE_DEFINITIONS = {
  "01_block": [
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 1, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 } },
  ],
  "02_wedge": [
    { orientation: 1, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 6, position: { x: 0, y: 0, z: 0 } },
  ],
  "03_pyramid": [
    { orientation: 0, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 5, shape: 7, position: { x: 0, y: 0, z: 0 } },
  ],
  "04_invpyramid": [
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 2, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 1, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 5, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 5, shape: 8, position: { x: 0, y: 0, z: 0 } },
  ],
  "05_wedge_2": [
    { orientation: 1, shape: 9, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 11, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 21, position: { x: 0, y: 0, z: 0 } },
    { orientation: 1, shape: 10, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 5, shape: 22, position: { x: 0, y: 0, z: -1 } },
    { orientation: 0, shape: 12, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
  ],
  "06_pyramid_2": [
    { orientation: 0, shape: 11, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 0, shape: 12, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 3, shape: 9, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 3, shape: 10, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 4, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 5, shape: 27, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 28, position: { x: 0, y: 0, z: -1 } },
  ],
  "07_invpyramid_2": [
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 2, shape: 11, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 1, shape: 9, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 5, shape: 47, position: { x: 0, y: 0, z: 0 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 1, shape: 10, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 2, shape: 12, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 5, shape: 48, position: { x: 0, y: 0, z: -1 } },
    { orientation: 5, shape: 2, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
  ],
  "08_wedge_4": [
    { orientation: 1, shape: 13, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 17, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 1, shape: 14, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 0, shape: 18, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 1, shape: 15, position: { x: 0, y: 0, z: -2 }, rotation: 1 },
    { orientation: 1, shape: 16, position: { x: 0, y: 0, z: -3 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 0, shape: 20, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 0, shape: 19, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 5, shape: 23, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 24, position: { x: 0, y: 0, z: -1 } },
    { orientation: 5, shape: 25, position: { x: 0, y: 0, z: -2 } },
    { orientation: 5, shape: 26, position: { x: 0, y: 0, z: -3 } },
  ],
  "09_pyramid_4": [
    { orientation: 0, shape: 17, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 2, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 13, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 5, shape: 29, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 30, position: { x: 0, y: 0, z: -1 } },
    { orientation: 5, shape: 31, position: { x: 0, y: 0, z: -2 } },
    { orientation: 5, shape: 32, position: { x: 0, y: 0, z: -3 } },
    { orientation: 0, shape: 18, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 0, shape: 19, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 0, shape: 20, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 3, shape: 14, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 15, position: { x: 0, y: 0, z: -2 }, rotation: 1 },
    { orientation: 3, shape: 16, position: { x: 0, y: 0, z: -3 }, rotation: 1 },
  ],
  "10_invpyramid_4": [
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 2, shape: 17, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 1, shape: 13, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 5, shape: 49, position: { x: 0, y: 0, z: 0 } },
    { orientation: 5, shape: 50, position: { x: 0, y: 0, z: -1 } },
    { orientation: 5, shape: 51, position: { x: 0, y: 0, z: -2 } },
    { orientation: 5, shape: 52, position: { x: 0, y: 0, z: -3 } },
    { orientation: 2, shape: 18, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 2, shape: 19, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 2, shape: 20, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 1, shape: 14, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 1, shape: 15, position: { x: 0, y: 0, z: -2 }, rotation: 1 },
    { orientation: 1, shape: 16, position: { x: 0, y: 0, z: -3 }, rotation: 1 },
    { orientation: 5, shape: 2, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
  ],
  "11_pyramid_2x2": [
    { orientation: 0, shape: 11, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 9, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 12, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 4, shape: 10, position: { x: -1, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 2, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 2, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 2, shape: 33, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 34, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 34, position: { x: -1, y: 0, z: 0 } },
  ],
  "12_pyramid_2x4": [
    { orientation: 0, shape: 17, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 9, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 18, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 4, shape: 10, position: { x: -1, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 9, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 20, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 0, shape: 19, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 3, shape: 10, position: { x: 0, y: 0, z: -3 }, rotation: 1 },
    { orientation: 3, shape: 9, position: { x: 0, y: 0, z: -2 }, rotation: 1 },
    { orientation: 3, shape: 10, position: { x: -1, y: 0, z: -1 }, rotation: 1 },
    { orientation: 2, shape: 38, position: { x: 0, y: 0, z: -3 } },
    { orientation: 2, shape: 37, position: { x: 0, y: 0, z: -2 } },
    { orientation: 2, shape: 36, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 35, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 37, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 38, position: { x: -1, y: 0, z: -1 } },
  ],
  "13_pyramid_4x4": [
    { orientation: 0, shape: 17, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 13, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 0, shape: 18, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 4, shape: 14, position: { x: -1, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 4, shape: 15, position: { x: -2, y: 0, z: 0 }, rotation: 2 },
    { orientation: 4, shape: 16, position: { x: -3, y: 0, z: 0 }, rotation: 2 },
    { orientation: 0, shape: 19, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 0, shape: 20, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 3, shape: 1, position: { x: -2, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 3, shape: 2, position: { x: 0, y: 0, z: -3 }, rotation: 1 },
    { orientation: 3, shape: 2, position: { x: -1, y: 0, z: -2 }, rotation: 1 },
    { orientation: 3, shape: 2, position: { x: -2, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 2, position: { x: -3, y: 0, z: 0 }, rotation: 1 },
    { orientation: 2, shape: 46, position: { x: 0, y: 0, z: -3 } },
    { orientation: 2, shape: 46, position: { x: -1, y: 0, z: -2 } },
    { orientation: 2, shape: 46, position: { x: -2, y: 0, z: -1 } },
    { orientation: 2, shape: 46, position: { x: -3, y: 0, z: 0 } },
    { orientation: 2, shape: 45, position: { x: 0, y: 0, z: -2 } },
    { orientation: 2, shape: 45, position: { x: -1, y: 0, z: -1 } },
    { orientation: 2, shape: 45, position: { x: -2, y: 0, z: 0 } },
    { orientation: 2, shape: 44, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 44, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 43, position: { x: 0, y: 0, z: 0 } },
  ],
  "14_invpyramid_2x2": [
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 3 },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -1 }, rotation: 3 },
    { orientation: 4, shape: 1, position: { x: -1, y: 0, z: 0 }, rotation: 2 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 54, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 2, position: { x: 0, y: 0, z: -1 }, rotation: 2 },
    { orientation: 2, shape: 54, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 2, position: { x: -1, y: 0, z: 0 }, rotation: 2 },
    { orientation: 2, shape: 53, position: { x: -1, y: 0, z: -1 } },
    { orientation: 5, shape: 11, position: { x: 0, y: 0, z: -1 } },
    { orientation: 5, shape: 12, position: { x: -1, y: 0, z: -1 } },
    { orientation: 1, shape: 9, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 1, shape: 10, position: { x: -1, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -1 } },
  ],
  "15_invpyramid_2x4": [
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 4, shape: 1, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 11, position: { x: -1, y: 0, z: 0 }, rotation: 3 },
    { orientation: 2, shape: 12, position: { x: -1, y: 0, z: -1 }, rotation: 3 },
    { orientation: 2, shape: 11, position: { x: 0, y: 0, z: -2 }, rotation: 3 },
    { orientation: 2, shape: 12, position: { x: 0, y: 0, z: -3 }, rotation: 3 },
    { orientation: 5, shape: 11, position: { x: 0, y: 0, z: -3 } },
    { orientation: 5, shape: 12, position: { x: -1, y: 0, z: -3 } },
    { orientation: 1, shape: 13, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 1, shape: 14, position: { x: -1, y: 0, z: -1 }, rotation: 1 },
    { orientation: 1, shape: 15, position: { x: -1, y: 0, z: -2 }, rotation: 1 },
    { orientation: 1, shape: 16, position: { x: -1, y: 0, z: -3 }, rotation: 1 },
    { orientation: 2, shape: 58, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 57, position: { x: -1, y: 0, z: -1 } },
    { orientation: 2, shape: 56, position: { x: -1, y: 0, z: -2 } },
    { orientation: 2, shape: 58, position: { x: 0, y: 0, z: -2 } },
    { orientation: 2, shape: 55, position: { x: -1, y: 0, z: -3 } },
    { orientation: 2, shape: 57, position: { x: 0, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: 0 } },
  ],
  "16_invpyramid_4x4": [
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: 0 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -1 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: 0 }, rotation: 1 },
    { orientation: 3, shape: 1, position: { x: -2, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 0, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 4, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 4, shape: 1, position: { x: -1, y: 0, z: 0 } },
    { orientation: 4, shape: 1, position: { x: -2, y: 0, z: 0 } },
    { orientation: 4, shape: 1, position: { x: -3, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: -1 } },
    { orientation: 2, shape: 1, position: { x: 0, y: 0, z: -2 } },
    { orientation: 2, shape: 1, position: { x: -1, y: 0, z: -1 } },
    { orientation: 2, shape: 1, position: { x: -1, y: 0, z: 0 } },
    { orientation: 2, shape: 1, position: { x: -2, y: 0, z: 0 } },
    { orientation: 2, shape: 2, position: { x: -3, y: 0, z: 0 }, rotation: 2 },
    { orientation: 2, shape: 2, position: { x: -2, y: 0, z: -1 }, rotation: 2 },
    { orientation: 2, shape: 2, position: { x: -1, y: 0, z: -2 }, rotation: 2 },
    { orientation: 2, shape: 2, position: { x: 0, y: 0, z: -3 }, rotation: 2 },
    { orientation: 5, shape: 17, position: { x: 0, y: 0, z: -3 } },
    { orientation: 5, shape: 18, position: { x: -1, y: 0, z: -3 } },
    { orientation: 5, shape: 19, position: { x: -2, y: 0, z: -3 } },
    { orientation: 5, shape: 20, position: { x: -3, y: 0, z: -3 } },
    { orientation: 1, shape: 13, position: { x: -3, y: 0, z: 0 }, rotation: 1 },
    { orientation: 1, shape: 14, position: { x: -3, y: 0, z: -1 }, rotation: 1 },
    { orientation: 1, shape: 15, position: { x: -3, y: 0, z: -2 }, rotation: 1 },
    { orientation: 1, shape: 16, position: { x: -3, y: 0, z: -3 }, rotation: 1 },
    { orientation: 2, shape: 66, position: { x: -3, y: 0, z: 0 } },
    { orientation: 2, shape: 66, position: { x: -2, y: 0, z: -1 } },
    { orientation: 2, shape: 66, position: { x: -1, y: 0, z: -2 } },
    { orientation: 2, shape: 66, position: { x: 0, y: 0, z: -3 } },
    { orientation: 2, shape: 65, position: { x: -3, y: 0, z: -1 } },
    { orientation: 2, shape: 65, position: { x: -2, y: 0, z: -2 } },
    { orientation: 2, shape: 65, position: { x: -1, y: 0, z: -3 } },
    { orientation: 2, shape: 64, position: { x: -3, y: 0, z: -2 } },
    { orientation: 2, shape: 64, position: { x: -2, y: 0, z: -3 } },
    { orientation: 2, shape: 63, position: { x: -3, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: -3, y: 0, z: 0 } },
    { orientation: 3, shape: 1, position: { x: -2, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: -3, y: 0, z: -1 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: -2, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: 0, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: -1, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: -3, y: 0, z: -2 } },
    { orientation: 3, shape: 1, position: { x: -2, y: 0, z: -3 } },
    { orientation: 3, shape: 1, position: { x: -3, y: 0, z: -3 } },
  ],
} as const;

export type BasicBlockType = keyof typeof BASIC_BLOCK_SURFACE_DEFINITIONS;

export function isBasicBlockType(value: unknown): value is BasicBlockType {
  return typeof value === "string" && value in BASIC_BLOCK_SURFACE_DEFINITIONS;
}
