import { type Surface } from "@sw-file-lib/xml";

export const BLOCK_SURFACE_DEFINITIONS = {
  "01_block": [
    { orientation: 0, shape: 1 },
    { orientation: 1, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, shape: 1 },
  ] as Surface[],
  "02_wedge": [
    { orientation: 0, rotation: 2, shape: 2 },
    { orientation: 1, rotation: 1, shape: 2 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 6 },
  ] as Surface[],
  "03_pyramid": [
    { orientation: 0, rotation: 2, shape: 2 },
    { orientation: 3, rotation: 1, shape: 2 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 7 },
  ] as Surface[],
  "04_invpyramid": [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 2 },
    { orientation: 2, rotation: 2, shape: 2 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 8 },
    { orientation: 5, rotation: 3, shape: 2 },
  ] as Surface[],
  "05_wedge_2": [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 1, rotation: 1, shape: 9 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 21 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 22 },
  ] as Surface[],
  "06_pyramid_2": [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 3, rotation: 1, shape: 9 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 27 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 28 },
  ] as Surface[],
  "07_invpyramid_2": [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 9 },
    { orientation: 2, rotation: 3, shape: 11 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 47 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 48 },
    { position: { z: -1 }, orientation: 5, rotation: 3, shape: 2 },
  ] as Surface[],
  "08_wedge_4": [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 1, rotation: 1, shape: 13 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 23 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 24 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 25 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 26 },
  ] as Surface[],
  "09_pyramid_4": [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 3, rotation: 1, shape: 13 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 29 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 30 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 3, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 31 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 32 },
  ] as Surface[],
  "10_invpyramid_4": [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 13 },
    { orientation: 2, rotation: 3, shape: 17 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 49 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 2, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 50 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 2, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 51 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 2, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 52 },
    { position: { z: -3 }, orientation: 5, rotation: 3, shape: 2 },
  ] as Surface[],
  "11_pyramid_2x2": [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 2, rotation: 0, shape: 33 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 9 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 34 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 34 },
    { position: { x: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 10 },
  ] as Surface[],
  "12_pyramid_2x4": [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 2, rotation: 0, shape: 35 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 9 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 36 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 37 },
    { position: { z: -2 }, orientation: 3, rotation: 1, shape: 9 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 38 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 10 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 37 },
    { position: { x: -1 }, orientation: 3, rotation: 1, shape: 9 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 10 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 38 },
    { position: { x: -1, z: -1 }, orientation: 3, rotation: 1, shape: 10 },
  ] as Surface[],
  "13_pyramid_4x4": [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 2, rotation: 0, shape: 43 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 13 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 44 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 44 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 14 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -1, z: -2 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -2 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { x: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2 }, orientation: 4, rotation: 2, shape: 15 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -2, z: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -3 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -3 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -3 }, orientation: 4, rotation: 2, shape: 16 },
  ] as Surface[],
  "14_invpyramid_2x2": [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 54 },
    { position: { z: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 11 },
    { position: { x: -1 }, orientation: 1, rotation: 1, shape: 9 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 54 },
    { position: { x: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 53 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 5, rotation: 0, shape: 12 },
  ] as Surface[],
  "15_invpyramid_2x4": [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, shape: 1 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 58 },
    { position: { z: -2 }, orientation: 2, rotation: 3, shape: 11 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 57 },
    { position: { z: -3 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 11 },
    { position: { x: -1 }, orientation: 1, rotation: 1, shape: 13 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 58 },
    { position: { x: -1 }, orientation: 2, rotation: 3, shape: 11 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 57 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 56 },
    { position: { x: -1, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { x: -1, z: -3 }, orientation: 2, rotation: 0, shape: 55 },
    { position: { x: -1, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 5, rotation: 0, shape: 12 },
  ] as Surface[],
  "16_invpyramid_4x4": [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, shape: 1 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 2, shape: 1 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { z: -3 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 17 },
    { position: { x: -1 }, orientation: 2, shape: 1 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 2, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -1, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -1, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 5, rotation: 0, shape: 18 },
    { position: { x: -2 }, orientation: 2, shape: 1 },
    { position: { x: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2 }, orientation: 4, shape: 1 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -2, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -2 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -2, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -3 }, orientation: 2, rotation: 0, shape: 64 },
    { position: { x: -2, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -3 }, orientation: 5, rotation: 0, shape: 19 },
    { position: { x: -3 }, orientation: 1, rotation: 1, shape: 13 },
    { position: { x: -3 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -3 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -3 }, orientation: 3, shape: 1 },
    { position: { x: -3 }, orientation: 4, shape: 1 },
    { position: { x: -3, z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { x: -3, z: -1 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -3, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { x: -3, z: -2 }, orientation: 2, rotation: 0, shape: 64 },
    { position: { x: -3, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { x: -3, z: -3 }, orientation: 2, rotation: 0, shape: 63 },
    { position: { x: -3, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -3 }, orientation: 5, rotation: 0, shape: 20 },
  ] as Surface[],
} as const;

export type BasicBlockType = keyof typeof BLOCK_SURFACE_DEFINITIONS;

export function isBasicBlockType(value: unknown): value is BasicBlockType {
  return typeof value === "string" && value in BLOCK_SURFACE_DEFINITIONS;
}
