name: Check

on:
  push:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dev-tools
        run: pnpm build:dev-tools

      - name: Debug 1
        run: pnpm exec which xml-schema-codegen
      - name: Debug 2
        run: ls -R packages/dev-tools/dist

      - name: Check
        run: pnpm check

      - name: Build
        run: pnpm build
